CONFIG_CPP=y
CONFIG_I2C=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_UART_LINE_CTRL=y

# USB console: nRF Connect SDK v3.4.0 / XIAO BLE board defaults.
CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=y
CONFIG_BUILD_OUTPUT_UF2=y
